### ISSUE TITLE
Create dummy oni driver

### ISSUE THREAD

**Issue by aacuevas** [jonnew/ONIX#24]
Having the ability to test the API without hardware would be useful for testing.

Using the driver interface it is possible to create a dummy driver that exposes fictional hardware with a fixed set of devices and streams to the API.

**Comment by samuelgarcia** [comment]
Ideally a simple read in loop binary file that represent multi channel signal with timed small chunk would perfect.

This driver would have the following  config params:
  * the binary file path
  * the sample rate
  * the dtype
  * channel count
  * buffer size
The timing would depend on sample rate and buffer size.

**Comment by jonnew** [comment]
The old code I was using to do this back when we were using Xillybus is [here](https://github.com/jonnew/open-ephys-pcie/blob/c6f697f10bcd9a60b35fd9be5fcd2020ccb786b3/api/liboni/liboni-test/firm_xilly.c#L1). This emulates all the signal, config, and high bandwidth read channels. It needs to be updates to work with the newer API. To do this, I would recommend turning this code into a driver as Aaron suggests.

**Comment by samuelgarcia** [comment]
Yes I saw it. It confusing why it is named xilly or riffa.
Why don't you put this inside driver folder.
Is it the way to go ?

**Comment by jonnew** [comment]
Yes, it is. Its not there because it predates the concept of a driver in this API.

**Comment by jonnew** [comment]
This was completed over in the liboni repo: https://github.com/jonnew/liboni/commit/43445c99342cd45fb0b8e41a54e0dc8040af2dcb

**Comment by samuelgarcia** [comment]
Good news. Thank you.
